### ISSUE TITLE
Debugging your Express apps on mobile devices

### ISSUE THREAD

**Issue by chrisajimenez** [porchdotcom/blog#8]
> Chris Jimenez <br/>
> Software Engineer <br/>
> Conversion <br/>
> I've been a software engineer at Porch since March 2015, with a focus on our Node / React stack.

# Debugging OSX node/express apps on mobile devices

I recently ran into an issue where I could not replicate some rendering problems we had with our [Careers page](https://porch.com/about/careers) on iOS. I'd like
to share a small collection of notes that I took in order to access my local machine's instance of the app with some physical test devices that I had access to. I will first go over how to enable your device to access the express app via a proxy, and then I will include a set of links to get you started with remote debugging using the chrome and safari dev tools that you are probably already used to.

## Setting up your proxy on Mac OSX

I’ll outline how to set up a SquidMan proxy (Thanks Valentina M and Zach Richards!)

* Download [SquidMan](http://squidman.net/squidman/)
* Install SquidMan

*Sometimes, there are issues with installation, read the “Helper Tool Issue” section of the squidman documentation.*

1. Ensure your mobile device is connected to the same network as your OSX device.

2. In the SquidMan preferences, set the port to 8888 (or any unused port)
<div align="center">
    <img src="https://cdn.porch.com/bootstrap/0web/engineering-blog/mobile-debugging/squidman-port.png" />
</div>

3. Go to “Clients” and click “New". Find your phones IP address and enter there. Or cover the entire submask your phone is in (ex 10.77.158.0/24)
* *if you don't know how to find your IP address, check these guides for [Android](https://help.simpletelly.com/support/solutions/articles/6000085149-how-to-find-your-android-device-ip-address) and [iOS](http://www.macinstruct.com/node/547)*
<div align="center">
    <img src="https://cdn.porch.com/bootstrap/0web/engineering-blog/mobile-debugging/squidman-ipaddress.png" />
</div>

4. Go to “Template”. Find the line "http_access deny to_localhost” and comment it out using “#”
<div align="center">
    <img src="https://cdn.porch.com/bootstrap/0web/engineering-blog/mobile-debugging/squidman-template.png" />
</div>

5. Save your preferences, and start the SquidMan proxy:
<div align="center">
    <img src="https://cdn.porch.com/bootstrap/0web/engineering-blog/mobile-debugging/squidman-proxy.png" />
</div>

There are now a few steps to go through on your phone:

1. In your phone’s wifi settings, select the network that your desktop is connected to, and set up a manual proxy.

2. Use your desktop’s IP address as the host

3. Use the port number from SquidMan as your port

Here are some references:

- Android: http://www.phonearena.com/news/How-to-set-up-a-proxy-server-connection-in-Android_id70310
- iPhone: http://www.amsys.co.uk/2012/05/how-to-setup-proxy-servers-in-ios/

Make sure your express app is running on your desktop

Access your app on your phone using lvh.me:{portNumber}. (For example, lvh.me:8080, if you are serving your express app on port 8080)

<div align="center">
    <div> Porch's FAQ </div>
    <img width="300px" src="https://cdn.porch.com/bootstrap/0web/engineering-blog/mobile-debugging/mobile-faq.png" />
</div>

Congrats! You are now able to access your express app using your phone!

*Normally, you would probably access your app using localhost:{portNumber} but this won't work properly, as your phone will try and access it's own localhost. Instead, using [lvh.me as a proxy](https://coderwall.com/p/-neplg/use-lvh-me-for-local-subdomain-testing) will target the requesting machine's localhost, in this case, the machine where the squidman proxy is running*

### Android:
http://www.greenbot.com/article/2457986/how-to-enable-developer-options-on-your-android-phone-or-tablet.html
- Enable your developer tools. Go to settings -> about phone/device/tablet -> click on the “Build Number” 7 times. (no joke)
- Then settings -> developer tools -> enable remote debugging

### iOS:
https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html
- Settings -> safari -> advanced -> turn on web inspector
Safari (desktop):

On safari desktop, you need to enable the dev tools.
- Preferences -> advanced -> show develop menu in menu bar

Debugging:

For ios/safari, I’ve found this guide to be helpful:
https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787

For android/chrome I’ve found this to be helpful:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

Thanks again! 

-- Chris Jimenez

<chrisj@porch.com>

**Comment by DarylThayil** [comment]
Installing squidman I had to do this 
<img width="731" alt="screenshot 2017-03-17 13 13 59" src="https://cloud.githubusercontent.com/assets/4453433/24061196/ad1802a4-0b13-11e7-9cb8-dfc3a44669a8.png">

**Comment by DarylThayil** [comment]
Use your desktop’s IP address as the host

Explain how to find this

**Comment by DarylThayil** [comment]
you say use desktop ip as host but for me its called server

**Comment by DarylThayil** [comment]
does it need to be an express app?

**Comment by DarylThayil** [comment]
Id consider renaming this because the glut of information is about accessing your service / front end from your phone and then debugging.

**Comment by DarylThayil** [comment]
Add a GIF of you debugging

**Comment by DarylThayil** [comment]
Add instructions to remove proxy and why

**Comment by tracieh** [comment]
Why the strange spacing in the first paragraph? Extra line breaks or something?
